drop database if exists szkola;
create database szkola;
use szkola;

create table uczniowie (
    id_uczen int primary key auto_increment,
    imie varchar(50),
    nazwisko varchar(50)
);

create table przedmioty (
    id_przedmiot int primary key auto_increment,
    nazwa varchar(50)
);

create table oceny (
    id_ocena int primary key auto_increment,
    id_uczen int,
    id_przedmiot int,
    ocena int,
    foreign key (id_uczen) references uczniowie(id_uczen),
    foreign key (id_przedmiot) references przedmioty(id_przedmiot)
);

insert into uczniowie (imie, nazwisko) values
('Jan', 'Kowalski'),
('Anna', 'Nowak'),
('Piotr', 'Zieliński'),
('Katarzyna', 'Wiśniewska'),
('Michał', 'Wójcik'),
('Agnieszka', 'Kowalczyk'),
('Tomasz', 'Kamiński'),
('Magdalena', 'Lewandowska'),
('Paweł', 'Zieliński'),
('Joanna', 'Szymańska'),
('Krzysztof', 'Woźniak'),
('Ewa', 'Dąbrowska'),
('Marcin', 'Kozłowski'),
('Monika', 'Jankowska'),
('Adam', 'Mazur'),
('Dorota', 'Kwiatkowska'),
('Łukasz', 'Krawczyk'),
('Barbara', 'Piotrowska'),
('Rafał', 'Grabowski'),
('Natalia', 'Zając'),
('Grzegorz', 'Pawlak'),
('Alicja', 'Michalska'),
('Marek', 'Król'),
('Karolina', 'Wróbel'),
('Wojciech', 'Nowicki'),
('Beata', 'Jabłońska'),
('Dariusz', 'Wieczorek'),
('Izabela', 'Majewska'),
('Sebastian', 'Stępień'),
('Patrycja', 'Olszewska'),
('Mateusz', 'Jaworski'),
('Sylwia', 'Malinowska'),
('Artur', 'Adamczyk'),
('Iwona', 'Górska'),
('Jacek', 'Włodarczyk'),
('Renata', 'Sikora'),
('Andrzej', 'Walczak'),
('Elżbieta', 'Baran'),
('Szymon', 'Rutkowski'),
('Agnieszka', 'Michalak'),
('Mariusz', 'Szewczyk'),
('Katarzyna', 'Ostrowska'),
('Tomasz', 'Tomaszewski'),
('Anna', 'Pietrzak'),
('Piotr', 'Zalewski'),
('Magdalena', 'Wróblewska'),
('Michał', 'Marciniak'),
('Joanna', 'Sadowska'),
('Paweł', 'Borkowski'),
('Krzysztof', 'Sokołowski'),
('Ewa', 'Czarnecka'),
('Marcin', 'Urbański'),
('Monika', 'Kubiak'),
('Adam', 'Lis'),
('Dorota', 'Kaczmarek'),
('Łukasz', 'Wysocki'),
('Barbara', 'Chmielewska'),
('Rafał', 'Kowal'),
('Natalia', 'Kołodziej'),
('Grzegorz', 'Kurek'),
('Alicja', 'Wilk'),
('Marek', 'Mazurek'),
('Karolina', 'Wesołowska'),
('Wojciech', 'Zawadzki'),
('Beata', 'Szczepańska'),
('Dariusz', 'Kozioł'),
('Izabela', 'Musiał'),
('Sebastian', 'Kucharski'),
('Patrycja', 'Mucha'),
('Mateusz', 'Sobczak'),
('Sylwia', 'Kowalik'),
('Artur', 'Kubiak'),
('Iwona', 'Kowalewska'),
('Jacek', 'Kaczmarczyk'),
('Renata', 'Włodarczyk'),
('Andrzej', 'Kowalski'),
('Elżbieta', 'Sikorska'),
('Szymon', 'Kowalczyk'),
('Agnieszka', 'Kowalska'),
('Mariusz', 'Kowalski'),
('Katarzyna', 'Kowalska'),
('Tomasz', 'Kowalski'),
('Anna', 'Kowalska'),
('Piotr', 'Kowalski'),
('Magdalena', 'Kowalska'),
('Michał', 'Kowalski'),
('Joanna', 'Kowalska'),
('Paweł', 'Kowalski'),
('Krzysztof', 'Kowalski'),
('Ewa', 'Kowalska'),
('Marcin', 'Kowalski'),
('Monika', 'Kowalska'),
('Adam', 'Kowalski'),
('Dorota', 'Kowalska'),
('Łukasz', 'Kowalski'),
('Barbara', 'Kowalska'),
('Rafał', 'Kowalski'),
('Natalia', 'Kowalska'),
('Grzegorz', 'Kowalski'),
('Alicja', 'Kowalska');

insert into przedmioty (nazwa) values
('Informatyka'),
('Matematyka'),
('Biologia'),
('Chemia'),
('Fizyka'),
('Geografia'),
('Historia'),
('Język polski'),
('Język angielski'),
('Język niemiecki'),
('Język francuski'),
('Język hiszpański'),
('Wiedza o społeczeństwie'),
('Wiedza o kulturze'),
('Muzyka'),
('Plastyka'),
('Wychowanie fizyczne'),
('Religia'),
('Etyka'),
('Podstawy przedsiębiorczości'),
('Technika'),
('Zajęcia artystyczne'),
('Zajęcia techniczne'),
('Zajęcia komputerowe'),
('Zajęcia sportowe'),
('Zajęcia teatralne'),
('Zajęcia muzyczne'),
('Zajęcia plastyczne'),
('Zajęcia taneczne'),
('Zajęcia językowe'),
('Zajęcia matematyczne'),
('Zajęcia przyrodnicze'),
('Zajęcia humanistyczne'),
('Zajęcia społeczne'),
('Zajęcia ekonomiczne'),
('Zajęcia informatyczne'),
('Zajęcia techniczne'),
('Zajęcia artystyczne'),
('Zajęcia sportowe'),
('Zajęcia teatralne'),
('Zajęcia muzyczne'),
('Zajęcia plastyczne'),
('Zajęcia taneczne'),
('Zajęcia językowe'),
('Zajęcia matematyczne'),
('Zajęcia przyrodnicze'),
('Zajęcia humanistyczne'),
('Zajęcia społeczne'),
('Zajęcia ekonomiczne');

insert into oceny (id_uczen, id_przedmiot, ocena) values
(1, 1, 5),
(1, 2, 4),
(2, 1, 3),
(2, 2, 5),
(2, 1, 4),
(2, 2, 3),
(1, 1, 5),
(1, 2, 4),
-- ...998 more insert statements...
(100, 50, 3),
(100, 49, 4),
(100, 48, 5),
(100, 47, 2),
(100, 46, 3),
(100, 45, 4),
(100, 44, 5),
(100, 43, 2),
(100, 42, 3),
(100, 41, 4),
(100, 40, 5),
(100, 39, 2),
(100, 38, 3),
(100, 37, 4),
(100, 36, 5),
(100, 35, 2),
(100, 34, 3),
(100, 33, 4),
(100, 32, 5),
(100, 31, 2),
(100, 30, 3),
(100, 29, 4),
(100, 28, 5),
(100, 27, 2),
(100, 26, 3),
(100, 25, 4),
(100, 24, 5),
(100, 23, 2),
(100, 22, 3),
(100, 21, 4),
(100, 20, 5),
(100, 19, 2),
(100, 18, 3),
(100, 17, 4),
(100, 16, 5),
(100, 15, 2),
(100, 14, 3),
(100, 13, 4),
(100, 12, 5),
(100, 11, 2),
(100, 10, 3),
(100, 9, 4),
(100, 8, 5),
(100, 7, 2),
(100, 6, 3),
(100, 5, 4),
(100, 4, 5),
(100, 3, 2),
(100, 2, 3),
(100, 1, 4);

select * from uczniowie as u 
join oceny as o on u.id_uczen = o.id_uczen 
join przedmioty as p on o.id_przedmiot = p.id_przedmiot;

create view oceny_uczniow as
select u.imie, u.nazwisko, p.nazwa, o.ocena
from uczniowie as u
join oceny as o on u.id_uczen = o.id_uczen
join przedmioty as p on o.id_przedmiot = p.id_przedmiot;

select * from oceny_uczniow;